version: "3.8"

networks:
  default:
    external:
      name: local_network_dev

services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      default:
        ipv4_address: 172.18.0.5
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=psychofizz@pm.me
      - PGADMIN_DEFAULT_PASSWORD=lxpeace
    depends_on:
      - db
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - /Users/saikofisu/Documents/UNAH_2024/IIPAC2024/soft-eng/django-postgres-docker.nosync/app:/usr/src/app
    depends_on:
      - db

volumes:
  postgres_data:
